"""add relevant_link lists to extract_job_result_data

Revision ID: 0682a35ea2ad
Revises: 3b6078d2f4ac
Create Date: 2025-11-24 17:15:26.838681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0682a35ea2ad'
down_revision: Union[str, Sequence[str], None] = '3b6078d2f4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract_job_results', sa.Column('relevant_internal_links', sa.String(length=1024), nullable=True))
    op.add_column('extract_job_results', sa.Column('relevant_external_links', sa.String(length=1024), nullable=True))
    op.add_column('extract_job_results', sa.Column('relevant_file_links', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summarize_job_results', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('scrape_job_results', 'file_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'external_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'internal_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('extract_job_results', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('extract_job_results', 'relevancy',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('extract_job_results', 'trustworthiness',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('extract_job_results', 'relevant_file_links')
    op.drop_column('extract_job_results', 'relevant_external_links')
    op.drop_column('extract_job_results', 'relevant_internal_links')
    # ### end Alembic commands ###
