"""Add more fields to LLM data extraction tasks

Revision ID: 23ada8c48b41
Revises: 914169454f8e
Create Date: 2025-10-30 15:52:05.365575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ada8c48b41'
down_revision: Union[str, Sequence[str], None] = '914169454f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract_job_results', sa.Column('key_facts', sa.Text(), nullable=False))
    op.add_column('extract_job_results', sa.Column('key_quotes', sa.Text(), nullable=False))
    op.add_column('extract_job_results', sa.Column('key_figures', sa.Text(), nullable=False))
    op.add_column('summarize_job_results', sa.Column('key_facts', sa.Text(), nullable=False))
    op.add_column('summarize_job_results', sa.Column('key_quotes', sa.Text(), nullable=False))
    op.add_column('summarize_job_results', sa.Column('key_figures', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summarize_job_results', 'key_figures')
    op.drop_column('summarize_job_results', 'key_quotes')
    op.drop_column('summarize_job_results', 'key_facts')
    op.alter_column('scrape_job_results', 'file_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'external_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'internal_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.drop_column('extract_job_results', 'key_figures')
    op.drop_column('extract_job_results', 'key_quotes')
    op.drop_column('extract_job_results', 'key_facts')
    # ### end Alembic commands ###
