"""add model tracking to LLM responses

Revision ID: 42d481c223fd
Revises: 23ada8c48b41
Create Date: 2025-10-30 16:16:53.986130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d481c223fd'
down_revision: Union[str, Sequence[str], None] = '23ada8c48b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract_job_results', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('summarize_job_results', sa.Column('model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summarize_job_results', 'model')
    op.alter_column('scrape_job_results', 'file_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'external_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'internal_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.drop_column('extract_job_results', 'model')
    # ### end Alembic commands ###
