"""addd trustworthiness and relevanyc to llm output

Revision ID: 5f25ea90bb9e
Revises: 42d481c223fd
Create Date: 2025-10-30 16:42:40.081721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f25ea90bb9e'
down_revision: Union[str, Sequence[str], None] = '42d481c223fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract_job_results', sa.Column('trustworthiness', sa.Text(), default="", nullable=True))
    op.add_column('extract_job_results', sa.Column('relevancy', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NOT_RELEVANT', name='relevancy'), default="HIGH", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summarize_job_results', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('scrape_job_results', 'file_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'external_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('scrape_job_results', 'internal_links',
               existing_type=database.values.JSONList(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('extract_job_results', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('extract_job_results', 'relevancy')
    op.drop_column('extract_job_results', 'trustworthiness')
    # ### end Alembic commands ###
