"""move link extraction to scrape job table

Revision ID: 914169454f8e
Revises: c42e1e8e0088
Create Date: 2025-10-30 12:05:38.056494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914169454f8e'
down_revision: Union[str, Sequence[str], None] = 'c42e1e8e0088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('scrape_job_results', sa.Column("internal_links", sa.String(length=1024), nullable=False))
    op.add_column('scrape_job_results', sa.Column("external_links", sa.String(length=1024), nullable=False))
    op.add_column('scrape_job_results', sa.Column("file_links", sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_job_results', 'file_links')
    op.drop_column('scrape_job_results', 'external_links')
    op.drop_column('scrape_job_results', 'internal_links')
    op.add_column('extract_job_results', sa.Column('internal_links', sa.VARCHAR(length=1024), nullable=False))
    op.add_column('extract_job_results', sa.Column('external_links', sa.VARCHAR(length=1024), nullable=False))
    op.add_column('extract_job_results', sa.Column('file_links', sa.VARCHAR(length=1024), nullable=False))
    # ### end Alembic commands ###
