"""Add prompt column to extract_job_results and summarize_job_results

Revision ID: c42e1e8e0088
Revises: cbc50e5f7ae1
Create Date: 2025-10-14 08:52:00.238424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42e1e8e0088'
down_revision: Union[str, Sequence[str], None] = 'cbc50e5f7ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract_job_results', sa.Column('prompt', sa.Text(), nullable=False, default=''))
    op.add_column('summarize_job_results', sa.Column('prompt', sa.Text(), nullable=False, default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('summarize_job_results', 'prompt')
    # op.drop_column('extract_job_results', 'prompt')
    # ### end Alembic commands ###
