"""Initial migration

Revision ID: cbc50e5f7ae1
Revises:
Create Date: 2025-08-31 18:34:06.360446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbc50e5f7ae1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("url"),
    )
    op.create_table(
        "pages",
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_url"],
            ["sources.url"],
        ),
        sa.PrimaryKeyConstraint("url"),
    )
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("page_url", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_url"],
            ["pages.url"],
        ),
        sa.ForeignKeyConstraint(
            ["source_url"],
            ["sources.url"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "crawl_job_results",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("pages_crawled", sa.Integer(), nullable=False),
        sa.Column("total_pages_found", sa.Integer(), nullable=False),
        sa.Column("max_pages_limit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "extract_job_results",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("internal_links", sa.String(length=1024), nullable=False),
        sa.Column("external_links", sa.String(length=1024), nullable=False),
        sa.Column("file_links", sa.String(length=1024), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum("UNREVIEWED", "APPROVED", name="reviewstatus"),
            nullable=False,
            server_default="UNREVIEWED",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "job_errors",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "scrape_job_results",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "summarize_job_results",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "data_origin",
            sa.Enum(
                "ACADEMIC",
                "GOVERNMENT",
                "NEWS",
                "BLOG",
                "NON_PROFIT",
                name="dataorigin",
            ),
            nullable=False,
        ),
        sa.Column(
            "source_format",
            sa.Enum(
                "RESEARCH_PAPER",
                "ARTICLE",
                "DATA_REPOSITORY",
                "HISTORICAL_INFO",
                "POLICY",
                "LAW",
                "NARRATIVE",
                "DATA_VISUALIZATION",
                "LETTER",
                "GOVERNMENT_SOURCE",
                name="sourceformat",
            ),
            nullable=False,
        ),
        sa.Column(
            "focus_area",
            sa.Enum(
                "NON_HUMAN_ANIMALS",
                "HUMANS",
                "ENVIRONMENT",
                "COMMUNITY",
                "BUSINESS",
                name="focusarea",
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum("UNREVIEWED", "APPROVED", name="reviewstatus"),
            nullable=False,
            server_default="UNREVIEWED",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summarize_job_results")
    op.drop_table("scrape_job_results")
    op.drop_table("job_errors")
    op.drop_table("extract_job_results")
    op.drop_table("crawl_job_results")
    op.drop_table("jobs")
    op.drop_table("pages")
    op.drop_table("sources")
    # ### end Alembic commands ###
