"""Initial migration with all tables

Revision ID: fcd4b1791743
Revises: 
Create Date: 2025-08-29 22:58:46.405823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd4b1791743'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('pages',
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['source_url'], ['sources.url'], ),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), nullable=False),
    sa.Column('page_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['page_url'], ['pages.url'], ),
    sa.ForeignKeyConstraint(['source_url'], ['sources.url'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('scrape_job_results',
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), nullable=False),
    sa.Column('markdown', sa.TEXT(), nullable=False),
    sa.Column('html', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('crawl_job_results',
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pages_crawled', sa.INTEGER(), nullable=False),
    sa.Column('total_pages_found', sa.INTEGER(), nullable=False),
    sa.Column('max_pages_limit', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('extract_job_results',
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), nullable=False),
    sa.Column('internal_links', sa.TEXT(), nullable=False),
    sa.Column('external_links', sa.TEXT(), nullable=False),
    sa.Column('file_links', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_errors',
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('summarize_job_results',
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('data_origin', sa.VARCHAR(length=10), nullable=False),
    sa.Column('source_format', sa.VARCHAR(length=18), nullable=False),
    sa.Column('focus_area', sa.VARCHAR(length=17), nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summarize_job_results')
    op.drop_table('job_errors')
    op.drop_table('extract_job_results')
    op.drop_table('crawl_job_results')
    op.drop_table('scrape_job_results')
    op.drop_table('jobs')
    op.drop_table('pages')
    op.drop_table('sources')
    # ### end Alembic commands ###
